apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-monitoring-ingress
  namespace: event-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - events.kollurinikhil.2bd.net 
    secretName: event-monitoring-tls
  rules:
  - host: events.kollurinikhil.2bd.net 
    http:
      paths:
      - path: /api/events 
        pathType: Prefix
        backend:
          service:
            name: event-ingestor-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-service
            port:
              number: 80